/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package charactergenerator;

/**
 *
 * @author Mag
 */
public class SkillsFrame extends javax.swing.JFrame {

    /**
     * Creates new form SkillsFrame
     */
    public SkillsFrame() {
        initComponents();
    }

    public void clbSkillTitle(String value){
        lbSkillTitle.setText(value);
    }
    public void clbRequiredValue(String value){
        lbRequiredValue.setText(value);
    }
    public void clbClassValue(String value){
        lbClassValue.setText(value);
    }
    public void clbTypeValue(String value){
        lbTypeValue.setText(value);
    }
    public void clbLevelValue(String value){
        lbLevelValue.setText(value);
    }
    public void clbDesc(String value){
        lbDesc.setText(value);
    }
    public void clbFx(String value){
        lbFx.setText(value);
    }
    public void clbMaxDistValue(String value){
        lbMaxDistValue.setText(value);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSkillTitle = new javax.swing.JLabel();
        lbClassValue = new javax.swing.JLabel();
        lbRequiredValue = new javax.swing.JLabel();
        lbTypeValue = new javax.swing.JLabel();
        lbLevelValue = new javax.swing.JLabel();
        lbRequired = new javax.swing.JLabel();
        lbClass = new javax.swing.JLabel();
        lbType = new javax.swing.JLabel();
        lbLevel = new javax.swing.JLabel();
        lbFx = new javax.swing.JLabel();
        lbDesc = new javax.swing.JLabel();
        lbMaxDist = new javax.swing.JLabel();
        lbMaxDistValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Habilidades");
        setResizable(false);

        lbSkillTitle.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lbSkillTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSkillTitle.setText("??????");

        lbClassValue.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbClassValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbClassValue.setText("????");

        lbRequiredValue.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbRequiredValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbRequiredValue.setText("????");

        lbTypeValue.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbTypeValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTypeValue.setText("?");

        lbLevelValue.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbLevelValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbLevelValue.setText("?");

        lbRequired.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbRequired.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbRequired.setText("Requisitos:");

        lbClass.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbClass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbClass.setText("Classe:");

        lbType.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbType.setText("Tipo:");

        lbLevel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbLevel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbLevel.setText("Nível:");

        lbFx.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbFx.setText("??");
        lbFx.setAutoscrolls(true);
        lbFx.setName(""); // NOI18N
        lbFx.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lbDesc.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbDesc.setText("??");
        lbDesc.setAutoscrolls(true);
        lbDesc.setName(""); // NOI18N
        lbDesc.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lbMaxDist.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbMaxDist.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbMaxDist.setText("Distância Máxima:");

        lbMaxDistValue.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbMaxDistValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbMaxDistValue.setText("?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbSkillTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lbRequiredValue, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbClassValue, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTypeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLevel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLevelValue, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMaxDist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMaxDistValue, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbFx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lbRequired)
                    .addContainerGap(444, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSkillTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRequiredValue)
                    .addComponent(lbClass)
                    .addComponent(lbClassValue))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbType)
                    .addComponent(lbTypeValue)
                    .addComponent(lbLevel)
                    .addComponent(lbLevelValue)
                    .addComponent(lbMaxDist)
                    .addComponent(lbMaxDistValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbFx, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(lbRequired)
                    .addContainerGap(276, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkillsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkillsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkillsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkillsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SkillsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbClass;
    private javax.swing.JLabel lbClassValue;
    private javax.swing.JLabel lbDesc;
    private javax.swing.JLabel lbFx;
    private javax.swing.JLabel lbLevel;
    private javax.swing.JLabel lbLevelValue;
    private javax.swing.JLabel lbMaxDist;
    private javax.swing.JLabel lbMaxDistValue;
    private javax.swing.JLabel lbRequired;
    private javax.swing.JLabel lbRequiredValue;
    private javax.swing.JLabel lbSkillTitle;
    private javax.swing.JLabel lbType;
    private javax.swing.JLabel lbTypeValue;
    // End of variables declaration//GEN-END:variables
}