/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerador;

import info.Ajuda;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author raymag
 * Versão 1.5
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        spQuantidade.setValue(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfPrefixo = new javax.swing.JTextField();
        btPath = new javax.swing.JButton();
        spQuantidade = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        tfExt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btModel = new javax.swing.JButton();
        btHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador de Documentos");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Prefixo:");

        tfPrefixo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfPrefixo.setText("arq");

        btPath.setBackground(new java.awt.Color(102, 102, 255));
        btPath.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btPath.setText("Gerar Em");
        btPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPathActionPerformed(evt);
            }
        });

        spQuantidade.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Quantidade:");

        tfExt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfExt.setText("html");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Extensão:");

        btModel.setBackground(new java.awt.Color(147, 183, 183));
        btModel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btModel.setText("Customizar Modelo");
        btModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModelActionPerformed(evt);
            }
        });

        btHelp.setBackground(new java.awt.Color(204, 255, 255));
        btHelp.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btHelp.setText("Ajuda");
        btHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btPath))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPrefixo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfExt, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfPrefixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHelp)
                    .addComponent(btModel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPathActionPerformed
        Selecionar sel = new Selecionar();
        int qnt = (int) spQuantidade.getValue();
        int status = sel.fcPath.showOpenDialog(null);
        sel.setVisible(true);
        if(status == sel.fcPath.APPROVE_OPTION){
            sel.setVisible(false);
            //String path = sel.fcPath.getSelectedFile().getName();
            for(int i=1;i<=qnt;i++){
                //System.out.println(String.valueOf(i));
                File arq = new File(sel.fcPath.getSelectedFile()+"/"+tfPrefixo.getText()+i+"."+tfExt.getText());
                String path = sel.fcPath.getSelectedFile()+"/"+tfPrefixo.getText()+i+"."+tfExt.getText();
                //System.out.println(sel.fcPath.getSelectedFile()+"/"+tfPrefixo.getText()+i+".html");
                //System.out.println(spQuantidade.getValue());
                try {
                    arq.getParentFile().mkdirs();
                    arq.createNewFile();
                    File doc = new File(tfExt.getText()+".txt");
                    String model;
                    try (BufferedReader modelReader = new BufferedReader(new FileReader(doc))) {
                        model = "";
                        while(modelReader.ready()){
                            model += " "+modelReader.readLine();
                        }
                        
                        model = model.replace("!dt-docname",tfPrefixo.getText()+i);
                        model = model.replace("!dt-date",
                                new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
                    }
                    try (BufferedWriter pen = new BufferedWriter(new FileWriter(path))) {
                        pen.append(model);
                        /*if(tfExt.getText().equals("html")){
                        BufferedWriter pen = new BufferedWriter(new FileWriter(sel.fcPath.getSelectedFile()+"/"+tfPrefixo.getText()+i+"."+tfExt.getText()));
                        pen.append("<!DOCTYPE html>\n<html>"
                        + "<head>\n<title>"+tfPrefixo.getText()+i+"</title>\n</head>"
                        + "\n<body>\n</body>\n</html>");
                        pen.close();
                        }
                        if(tfExt.getText().equals("php")){
                        BufferedWriter pen = new BufferedWriter(new FileWriter(sel.fcPath.getSelectedFile()+"/"+tfPrefixo.getText()+i+"."+tfExt.getText()));
                        pen.append("<!DOCTYPE html>\n<html>");
                        pen.append("<head>\n<title>"+tfPrefixo.getText()+i+"</title>\n</head>\n<body>\n<?php"
                        + "\n?>\n</body>\n");
                        pen.append("</html>");
                        pen.close();
                        }*/
                    }
                } catch (IOException ex) {
                    //Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
                    
                }
            }
           // sel.setVisible(false);
            sel.dispose();
            JOptionPane.showMessageDialog(null, "Sucesso.");
        }
        else if(status == sel.fcPath.CANCEL_OPTION){
            sel.setVisible(false);
            sel.dispose();
        }
    }//GEN-LAST:event_btPathActionPerformed

    private void btModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModelActionPerformed
        String fileModel = tfExt.getText();
        File arq = new File(fileModel+".txt");
        if(arq.exists()){
            System.out.println("Doctriz - Modelo Existente");
            try {
                BufferedReader reader = new BufferedReader(new FileReader(fileModel+".txt"));
                String model = "";
                while(reader.ready()){
                    model += reader.readLine()+"\n";
                }
                //System.out.println("Doctriz \n - modelo: "+model);
                ModelEditor modeleditor = new ModelEditor();
                modeleditor.setModelType(fileModel);
                modeleditor.setModel(model);
                modeleditor.setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            System.out.println("Doctriz - Modelo Inexistente");
            //System.out.println(fileModel+".txt");
            try {
                PrintWriter pen = new PrintWriter(fileModel+".txt");
                pen.close();
                System.out.println("Doctriz - Modelo Criado");
                
                try {
                BufferedReader reader = new BufferedReader(new FileReader(fileModel+".txt"));
                String model = "";
                while(reader.ready()){
                    model += reader.readLine()+"\n";
                }
                //System.out.println("Doctriz \n - modelo: "+model);
                ModelEditor modeleditor = new ModelEditor();
                modeleditor.setModelType(fileModel);
                modeleditor.setModel(model);
                modeleditor.setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }   catch (IOException ex) {
                    Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btModelActionPerformed

    private void btHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHelpActionPerformed
        Ajuda ajuda = new Ajuda();
        ajuda.setVisible(true);
    }//GEN-LAST:event_btHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHelp;
    private javax.swing.JButton btModel;
    private javax.swing.JButton btPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner spQuantidade;
    private javax.swing.JTextField tfExt;
    private javax.swing.JTextField tfPrefixo;
    // End of variables declaration//GEN-END:variables
}
