/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plusinfo;

/**
 *
 * @author Mag
 */
public class Breed extends javax.swing.JFrame {

    /**
     * Creates new form Breed
     */
    String humanaInfo = "A raça humana surgiu em Pangeia há pouco tempo, no entanto é uma das raças mais"
                    + " versáteis e poderosas que se tem conhecimento. Você encontrará humanos em quase todos"
                    + " os lugares, fazendo quase todas as coisas. A cidade principal dos humanos é a capital do"
            + " Império de Brasília, localizada à leste de Gondwana. Humanos são simplórios e fracos em relação"
                    + " as demais raças, mas é justamente por isso que a raça Humana faz coisas que nenhuma outra"
                    + " é capaz.";
    String  anaInfo = "Os Anões são renomados por sua vitalidade e orientação nas escavações, montanhas e procura "
            + "por pedras e minerais preciosos. Anões não costumam passar de 1.55 M de altura, mas podem ser ágeis, "
            + "fortes e muito resistentes. A maioria deles vive em Monte Carlo, no Sul de Gondwana. Costumam ser "
            + "hospitaleiros, emotivos, sem frescura e cheios de fibra!";
    String elficaInfo = "Os Elfos são admirados por toda Pangeia. São famosos por sua afinidade para com a magia e "
            + "ligação com a natureza e a árvore de lifus. Ao redor do mundo, há muitas variantes da raça élfica mas,"
            + " no geral, são seres astutos, altos, olhos afiados, cabelos longos e lisos, possuem orelhas pontiagudas "
            + "e normalmente possuem pele de tonalidade clara. Dizem que todas as variantes élficas surgiram da"
            + " Floresta Atalante.";
    String orcInfo = "Os Orcs são seres grandalhões, de tonalidade esverdeada ou cinzenta, musculósos, orelhas pontudas, "
            + "e de hábitos considerados obscuros e desprezíveis (Como canibalismo, comer inimigos, estupro, etc). São "
            + "odiados e temidos em muitos lugares, mas são também conhecidos por sua força e braveza no campo de "
            + "batalha. A maioria dos grupos Orcs falam Espanhol e vivem na região de 'Los Andes'. Alguns desses grupos, "
            + "fazem parte da UFEG.";
    String goblinInfo = "Goblins são criaturas horripilantes. Possuem olhos e orelhas afiadas, narizes pontudos, "
            + "não mais que 1.40 de altura. Adoram sarcasmo, riqueza e explosões. Pode ser perigoso lidar com um, "
            + "mas costumam ser espetaculares em áreas diversas como a mecânica, advocacia, e pirotecnia, etc.";
    String gnomoInfo = "";
    String undeadInfo = "";
    String bestialInfo = "Os Bestiais são talvez um dos grupos de seres conscientes mais antigos. Podem ser descritos como"
            + " animais comuns da fauna global, só que maiores, humanóides e conscientes. Parecem possuir uma sabedoria"
            + " natural e ter uma ligação especial com a natureza.";
    String constructInfo = "";
    String repetilianoInfo = "";
    String draconicaInfo = "";
    String satiroInfo = "";
    String plantaeInfo = "";
    
    public Breed() {
        initComponents();
        lbDesc.setText("<html>"+humanaInfo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbBreed = new javax.swing.JComboBox<>();
        btBreed = new javax.swing.JButton();
        lbDesc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Raças - Descrições Gerais");

        cbBreed.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        cbBreed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humana", "Anã", "Élfica", "Orc", "Goblina", "Bestial" }));

        btBreed.setBackground(new java.awt.Color(91, 153, 153));
        btBreed.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btBreed.setText("Ver");
        btBreed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBreedActionPerformed(evt);
            }
        });

        lbDesc.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbDesc.setText("??");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(cbBreed, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBreed, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBreed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBreed))
                .addGap(18, 18, 18)
                .addComponent(lbDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBreedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBreedActionPerformed
        String breed = String.valueOf(cbBreed.getSelectedItem());
        if(breed == "Humana"){
            lbDesc.setText("<html>"+humanaInfo);
        }
        if(breed == "Anã"){
            lbDesc.setText("<html>"+anaInfo);
        }
        if(breed == "Élfica"){
            lbDesc.setText("<html>"+elficaInfo);
        }
        if(breed == "Orc"){
            lbDesc.setText("<html>"+orcInfo);
        }
        if(breed == "Goblina"){
            lbDesc.setText("<html>"+goblinInfo);
        }
        /*if(breed == "Goblina"){
        lbDesc.setText("<html>"+goblinInfo);
        }
        if(breed == "Goblina"){
        lbDesc.setText("<html>"+goblinInfo);
        }*/
        if(breed == "Bestial"){
            lbDesc.setText("<html>"+bestialInfo);
        }
    }//GEN-LAST:event_btBreedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Breed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Breed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Breed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Breed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Breed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBreed;
    private javax.swing.JComboBox<String> cbBreed;
    private javax.swing.JLabel lbDesc;
    // End of variables declaration//GEN-END:variables
}
